name: geniusai_server
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python Environment
  - python=3.12
  - pip
  - setuptools
  - wheel
  - pyinstaller
  
  - pip:
    - open_clip_torch
    - rich
    - ollama
    - lmstudio
    - pillow
    - google-genai
    - openai
    - requests
    - chromadb
    - numpy
    - pandas
    - psutil
    - flask
    - waitress
